[package]
name = "rust_pathtracer"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24"
glam = "0.24"
rand = { version = "0.8", features = ["small_rng"] }
rayon = "1.7"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true